- name: DEV > Install packages
  ansible.builtin.package:
    name:
      - pre-commit
      - npm
    state: present
  become: true

- name: DEV > Install commitlint
  community.general.npm:
    name:  '@commitlint/cli'
    global: yes
    state: present
  become: true

- name: DEV > Install commitlint config-conventional
  community.general.npm:
    name:  '@commitlint/config-conventional'
    global: yes
    state: present
  become: true

- name: DEV > Install goimports globally
  ansible.builtin.shell: |
    source /etc/profile.d/go.sh
    go install golang.org/x/tools/cmd/goimports@latest
    cp "$(go env GOPATH)/bin/goimports" /usr/local/bin/goimports
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH }}"
  become: true
