daemon:
  id_path: /opt/realm_data/realm.id
  etcd_data_dir: /opt/realm_data/etcd
  cni_path: /opt/cni/bin
  volumes_pool: realmpool
  listen_address: 0.0.0.0

nodes:
  lab1:
    url: http://192.168.1.54:9000
  lab2:
    url: http://192.168.1.55:9000
  lab3:
    url: http://192.168.1.65:9000

loads:
  web:
    node: lab1
    driver: container
    driver_config:
      image: docker.io/nginx
    depends_on:
      - web2

  web2:
    node: lab1
    driver: container
    driver_config:
      image: docker.io/nginx
    depends_on:
      - netcat

  netcat:
    node: lab1
    driver: process
    driver_config:
      start_cmd: nc
      stop_signal: SIGHUP
      depends_on:
        - web
