nodes:
  lab1:
    url: http://192.168.105.2:9000
    driver: linux
    driver_config:
      wol: true
      MAC: 12:23:44:55:66:77

  vm1:
    url: http://192.168.105.2:9000
    driver: linux

  lab2:
    url: http://192.168.105.3:9000

loads:
  web:
    node: lab1
    driver: container
    driver_config:
      image: docker.io/nginx
    depends_on:
      - web2

  web2:
    node: lab1
    driver: container
    driver_config:
      image: docker.io/nginx
    depends_on:
      - netcat

  netcat:
    node: lab2
    driver: process
    driver_config:
      start_cmd: nc
      stop_signal: SIGHUP
      depends_on:
        - web
