- name: CADDY > Install prerequisites
  ansible.builtin.package:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
    state: present
  become: true

- name: CADDY > Add GPG key
  ansible.builtin.shell: |
    curl -1sLf "{{ caddy_repo_key_url }}" | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  become: true
  
- name: CADDY > Add apt source
  get_url:
    url: "{{ caddy_repo_list_url }}"
    dest: /etc/apt/sources.list.d/caddy-stable.list
  become: true
  
- name: CADDY > Update apt cache and install
  ansible.builtin.package:
    name: caddy
    update_cache: yes
    state: present
  become: true
  
- name: Ensure Caddy is enabled and running
  ansible.builtin.systemd:
    name: caddy
    enabled: yes
    state: started
