- name: CNI > Install iptables
  ansible.builtin.package:
    name:
      - iptables
      - bridge-utils
    state: present
  become: true

- name: CNI > Clone repo
  git:
    repo: https://github.com/containernetworking/cni.git
    dest: /tmp/cni
    force: yes

- name: CNI > Build cnitool
  shell: . /etc/profile.d/go.sh && go build .
  args:
    chdir: /tmp/cni/cnitool
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"

- name: CNI > Copy cnitool to /usr/local/bin
  copy:
    src: /tmp/cni/cnitool/cnitool
    dest: /usr/local/bin/cnitool
    remote_src: yes
    mode: '0755'
  become: true

- name: CNI > Clone plugins repo
  git:
    repo: https://github.com/containernetworking/plugins.git
    dest: /tmp/cni_plugins
    force: yes

- name: CNI > Build plugins
  shell: . /etc/profile.d/go.sh && ./build_linux.sh
  args:
    chdir: /tmp/cni_plugins
  become: true

- name: CNI > Ensure /opt/cni/bin exists
  file:
    path: "{{ cni_bin_dir }}"
    state: directory
    mode: '0755'
  become: true
  
- name: CNI > Copy built plugins to /opt/cni/bin
  copy:
    src: "/tmp/cni_plugins/bin/"
    dest: "{{ cni_bin_dir }}/"
    mode: '0755'
    remote_src: yes
  become: true
  
- name: CNI > Ensure /etc/cni/net.d exists
  file:
    path: "{{ cni_conf_dir }}/net.d"
    state: directory
    mode: '0755'
  become: true
