---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Setup required packages
  import_tasks: tasks/setup/packages.yml

- name: Setup Go
  import_tasks: tasks/setup/go.yml

- name: Setup development environment
  import_tasks: tasks/setup/dev-env.yml
  
- name: Setup Containerd
  import_tasks: tasks/setup/containerd.yml

- name: Setup CNI
  import_tasks: tasks/setup/cni.yml

- name: Setup Caddy
  import_tasks: tasks/setup/caddy.yml

- name: Setup ZFS
  import_tasks: tasks/setup/zfs.yml
