---
- name: Add Debian main + contrib sources (custom list)
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/custom.list
    content: |
      deb http://deb.debian.org/debian bookworm main contrib
      deb http://security.debian.org/debian-security bookworm-security main contrib
      deb http://deb.debian.org/debian bookworm-updates main contrib
    mode: '0644'
    owner: root
    group: root

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes

- name: Setup Containerd
  import_tasks: tasks/setup/containerd.yml

- name: Setup Git
  import_tasks: tasks/setup/git.yml

- name: Setup Go
  import_tasks: tasks/setup/go.yml

- name: Setup CNI
  import_tasks: tasks/setup/cni.yml

- name: Setup Caddy
  import_tasks: tasks/setup/caddy.yml

- name: Setup ZFS
  import_tasks: tasks/setup/zfs.yml

- name: Setup etcd
  import_tasks: tasks/setup/etcd.yml
