---
cni_clone_dir: /opt/cni
cni_plugins_clone_dir: /opt/cni_plugins
cni_bin_dir: /opt/cni/bin
cni_conf_dir: /etc/cni
caddy_repo_key_url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
caddy_repo_list_url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
zfs_local: false
zfs_pool_name: realmpool
zfs_device: /dev/sdb
