- name: Install realm on a cluster
  hosts: targets
  connection: ssh
  gather_facts: true
  vars_files:
    - vars/cluster.yml
  vars_prompt:
    - name: zfs_device
      prompt: "Enter ZFS device (e.g. /dev/sde). Warning: it can destroy the device filesystem"
      private: false
  tasks:
    - name: Install required packages
      import_tasks: tasks/setup/packages.yml

    - name: Setup Go
      import_tasks: tasks/setup/go.yml

    - name: Setup Containerd
      import_tasks: tasks/setup/containerd.yml

    - name: Setup CNI
      import_tasks: tasks/setup/cni.yml

    - name: Setup Caddy
      import_tasks: tasks/setup/caddy.yml

    - name: Setup ZFS
      import_tasks: tasks/setup/zfs.yml

    - name: Setup etcd
      import_tasks: tasks/setup/etcd.yml

    - name: Setup realmd
      import_tasks: tasks/setup/realmd.yml
